[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; 🚀 关键：根据 README 要求设置右/左手和 USB 串口
build_flags = 
    -D RIGHT_HAND
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; ⚡ 波特率
monitor_speed = 921600

lib_deps = 
    madhephaestus/ESP32Servo @ ^3.0.5
    https://github.com/ftservo/FTServo_Arduino.git